### ISSUE TITLE
Proof-checking Collated Tables

### ISSUE THREAD

**Issue by ebeshero** [ebeshero/Pittsburgh_Frankenstein#20]
@Rikkm @ebeshero
Between us we will proof-check the editions using our 33 output collation tables, C_1 to C_33.
1) Verify questionable passages of text in the PDFs
2) Make corrections in the plain text files AND 1818_full.xml, 1823_full.xml, 1831_full.xml  (Elisa will transform those into their fullFlat counterparts for collation.) 
3) As you complete checking a collation unit, list it here. This task is complete when all 33 units are marked as checked.

Rikk is assigned C_1 to C_16: edits completed.
Elisa is assigned C_17 to C_33
Rikk reassigned C_17 to C_33 (02/17/2018)
Rikk edited C_17 - C_21 (02/24/2018)
Rikk edited C_22 - C_27 (02/25/2018)
Rikk edited C_28 - C_33 (03/03/2018)

edits to 1818_full.xml, 1823_full.xml, and 1831_full.xml complefed in preparation for round 2 collation transformation to fullFlat.xml versions.

**Comment by Rikkm** [comment]
Edits to 1818_full.xml, 1823_full.xml, and 1831_full.xml completed in preparation for round 2 collation transformation to fullFlat.xml versions.
